In [116]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Liguagem Python usada neste Jupyter Notebbok', python_version())

Versão da Liguagem Python usada neste Jupyter Notebbok 3.11.7


# NumPy
<a href="https://numpy.org" target="_blank">https://numpy.org</a>

In [117]:
# Importando o NumPy
import numpy as np

In [118]:
np.__version__

'1.26.4'

In [119]:
# Instrução para instalar uma versão exata do pacote em python
# !pip install numpy==1.22.3

# Criando Arrays NumPy

In [120]:
# Array criado a partir de uma lista Python
arr1 = np.array([10,21,32,43,48,15,76,57,89])

In [121]:
# Imprimindo o tamanho do array
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [122]:
# Um objeto do tipo ndarray é um recipiente multidimensional de items do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [123]:
# Verificando o formato do array
arr1.shape

(9,)

In [124]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [125]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [126]:
# Cri uma lista de índices
indices = [1,2,5,6]

In [127]:
# Imprimindo os elementos dos índices
arr1[indices]

array([21, 32, 15, 76])

In [128]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [129]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [130]:
arr1[mask]

array([10, 32, 48, 76])

In [131]:
# Alterando um elemento do array
arr1[0] = 100

In [132]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [133]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!


`Um array NumPy é uma estrutura de dados multidemensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional(ou ndarray), que é uma grande homogênia de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.
Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são impelemntados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPU`

<img src="../arquivos/array.png">

In [134]:
# Criando o array
arr2 = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 

In [135]:
arr2

array([[[1, 5, 2, 1],
        [4, 3, 5, 6],
        [6, 3, 0, 6],
        [7, 3, 5, 0],
        [2, 3, 3, 5]],

       [[2, 2, 3, 1],
        [4, 0, 0, 5],
        [6, 3, 2, 1],
        [5, 1, 0, 0],
        [0, 1, 9, 1]],

       [[3, 1, 4, 2],
        [4, 1, 6, 0],
        [1, 2, 0, 6],
        [8, 3, 4, 0],
        [2, 0, 2, 8]]])

In [136]:
# Verificando o formato do array
arr2.shape

(3, 5, 4)

In [137]:
# Criando o array
arr3 = np.array(
        [   
            [
                [1, 5],
                [4, 3],
                [6, 3]
            ],

            [   
                [2, 2],
                [4, 0],
                [6, 3]
            ],

            [
                [3, 1],
                [4, 1],
                [1, 2]
            ],
            [
                [3, 1],
                [4, 1],
                [1, 2]
            ]
        ]
    )

In [138]:
arr3

array([[[1, 5],
        [4, 3],
        [6, 3]],

       [[2, 2],
        [4, 0],
        [6, 3]],

       [[3, 1],
        [4, 1],
        [1, 2]],

       [[3, 1],
        [4, 1],
        [1, 2]]])

In [139]:
# Imprimindo o formato do array
arr3.shape

(4, 3, 2)

In [140]:
# Indexando um elemento do array
arr3[1,2,0]

6

In [141]:
arr2

array([[[1, 5, 2, 1],
        [4, 3, 5, 6],
        [6, 3, 0, 6],
        [7, 3, 5, 0],
        [2, 3, 3, 5]],

       [[2, 2, 3, 1],
        [4, 0, 0, 5],
        [6, 3, 2, 1],
        [5, 1, 0, 0],
        [0, 1, 9, 1]],

       [[3, 1, 4, 2],
        [4, 1, 6, 0],
        [1, 2, 0, 6],
        [8, 3, 4, 0],
        [2, 0, 2, 8]]])

# Funções NumPy

In [142]:
# A função array() cria um array NumPy
arr4 = np.array([1,2,3,4,5])

In [143]:
print(arr4)

[1 2 3 4 5]


In [144]:
# Verificando o tipo do objeto
type(arr4)

numpy.ndarray

In [145]:
# Verificando os métodos: digite "." e pressione a tecla Tan para visualizar os métodos disponíveis em objetos NumPy
arr4

array([1, 2, 3, 4, 5])

In [146]:
# Usando métodos do array Numpy
arr4.cumsum()

array([ 1,  3,  6, 10, 15])

In [147]:
arr4.cumprod()

array([  1,   2,   6,  24, 120])

In [148]:
# Verificando as funções para manipular objetos NumPy
np

<module 'numpy' from '/home/mauro-lucio/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>

In [149]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr5 = np.arange(0,50,5)

In [150]:
print(arr5)

[ 0  5 10 15 20 25 30 35 40 45]


In [151]:
# Verificando o tipo do objeto
type(arr5)

numpy.ndarray

In [152]:
# Formato do array
np.shape(arr5)

(10,)

In [153]:
print(arr5.dtype)

int64


In [157]:
# Cria um array preenchido com zeros
arr6 = np.zeros(10)

In [155]:
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [158]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr7 = np.eye(3)

In [159]:
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [161]:
# Os valores passados como parâmetro, formam uma diagonal
arr8 = np.diag(np.array([1,2,3,4]))

In [162]:
print(arr8)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [163]:
# Array de valores booleanos
arr9 = np.array([True, False, False, True])

In [164]:
print(arr9)

[ True False False  True]


In [165]:
# Array de Strings
arr10 = np.array(['Linguagem Python','Linguagem R','Linguagem Julia'])

In [166]:
print(arr10)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


`A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo específico. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulções.`</br>
`O método linspace (linearly spaced vector) retorna um número de valores igualmente distribuídos no intervalo especificado.`